### ISSUE TITLE
impossible de se connecter

### ISSUE THREAD

**Issue by clubapplets-server** [ApplETS/Notre-Dame-v3#251] opened 2020-12-05 08:16 UTC
**What happened:**
```
impossible de se connecter
```

**Version:** 3.0.0-beta (31292)

**Operating system:** Android 10

**Model:** samsung SM-G975W

**Memory:** 63% (4.59 GB used out of 7.29 GB)

**Capacity:** 40% (43.3 GB used out of 109 GB)

**Locale:** Canada French

**Network:** 

**WiFi:** Connected

**Logs:** [View](http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/52/awesome_logs) 

**Attachments:** 

![screenshot_1607156126233.png](http://buglife.s3.amazonaws.com/report_attachments/3f845a1200cad9263960745c939d4ef49553128f/original/screenshot_1607156126233.png?1607156189)

**URL:** http://buglife.com/apps/etsmobile-beta-6fc235f7-1944-4ba8-bb15-6d69813d2e7a/reports/52

Reported via Buglife

**Comment by apomalyn** [comment] 2020-12-05 12:47
Duplicate of #244

**Closed as completed** 2020-12-05 12:47 UTC
